### ISSUE TITLE
Match platform without considering case

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/ggr#284]
And probably browser name and version.

**Comment by martingrossmann** [comment]
Hello @vania-pooh, I want to push this issue back to top because that is really tricky.

Using Chrome with 
```java
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.setBrowserVersion("106");
chromeOptions.setCapability(<platformCap>, <value>); // see examples above

WebDriver driver = new RemoteWebDriver(<myUrl>, chromeOptions);
```

__Setting up the GGR config with `platform="LINUX"`:__  (as it's documented)
This does not work:
* `chromeOptions.setCapability(CapabilityType.PLATFORM_NAME, Platform.LINUX);`
* `chromeOptions.setCapability(CapabilityType.PLATFORM_NAME, "LINUX");`
* `chromeOptions.setCapability("platformName", "LINUX");`
* `chromeOptions.setCapability(CapabilityType.PLATFORM_NAME, "linux");`
 
This is working, but this cap is deprecated:
* `chromeOptions.setCapability(CapabilityType.PLATFORM, Platform.LINUX);` 

__Setting up the GGR config with `platform="linux"`:__
All listed configs are working, except 
* `chromeOptions.setCapability(CapabilityType.PLATFORM, Platform.LINUX);`
* `chromeOptions.setCapability(CapabilityType.PLATFORM, "LINUX");`

__Workaround__
So the current documentation is not valid. With the current version the platform should setup with lower cases.


__Tested with__
* Selenium 4.7.2
* GGR 1.6.12
* Seleonid 1.10.9
* Chrome 106

**Comment by vania-pooh** [comment]
Need to check this one more time. Actually platform capability is rarely used. We mainly recommend relying on browser name and version.

**Comment by martingrossmann** [comment]
Thank you!

Well, we have to use platform cap because we have a mixed grid with linux and windows nodes.

**Comment by vania-pooh** [comment]
Fixed.
