### ISSUE TITLE
401 Unauthorized on GGR

### ISSUE THREAD

**Issue by upenbendre** [aerokube/ggr#297]
I am facing the exact same issue as #176, but it could not be resolved using the same fix.
I get a 401 Unauthorized, when running the test:
"http://test:testpassword@<ip_address>:4444/wd/hub"
as you can see my password does not contain any special characters.

if I enter http://test:testpassword@10.222.26.74:4444/quota on the browser , it still prompts me for a username and password. If I enter the same credentials, it still gives me a '401 Unauthorized"

there are no messages in the ggr container log. All I have is:
2019/11/20 12:37:56 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file is "/etc/grid-router/users.htpasswd"]
2019/11/20 12:37:56 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Loading configuration files from "/etc/grid-router/quota"]

My quota file is /etc/grid-router/quota/test.xml

The UI URL at port 8080 correctly shows this ggr linked to all the selenoid hosts, and the total quota count.

I have also set up the user and password correctly using htpasswd

**Comment by vania-pooh** [comment]
@upenbendre could you show the command used to create `users.htpasswd` file?

**Comment by jsa34** [comment]
Hello,

Getting the same issues here.

If I send tests to an individual grid, it's fine.

Using GGR I get the following response in test suite:
org.openqa.selenium.WebDriverException: 
Unable to parse remote response: 401 Unauthorized

Caused by: org.openqa.selenium.json.JsonException: 
Expected to read a START_MAP but instead have: NUMBER. Last 0 characters read: 
Build info: version: '4.0.0-alpha-3', revision: '8c567de6dc'
System info: host: 'xxx', ip: '10.0.32.174', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1062.9.1.el7.x86_64', java.version: '1.8.0_232'
Driver info: driver.version: RemoteWebDriver

**Comment by jsa34** [comment]
If it is any help, the issues appeared after the VM was updated, which included updating the docker API version from 1.39 to 1.40

**Comment by jsa34** [comment]
Same logs for GGR node as reported in original post:
2020/01/08 18:12:44 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file is "/etc/grid-router/users.htpasswd"]
2020/01/08 18:12:44 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Loading configuration files from "/etc/grid-router/quota"]

**Comment by jsa34** [comment]
Fixed.... just updated the username and password in the file and it seems happy again... not sure why it suddenly needed that, but hey ho, fixed!

**Comment by jsa34** [comment]
Argh- the issue returned suddenly, and I tried resetting the password to no avail.

Sending tests to the individual grids works fine, and I even tried starting a manual session through GGR-UI, but this no longer works.  I am at a loss as to what is happening because I can't see any errors logged anywhere...

**Comment by jsa34** [comment]
I have even tried removing the GGR container, creating a new one and no luck.

I have tried deleting the .htpasswd file and recreating it, and then doing the above, but no luck

**Comment by vania-pooh** [comment]
@upenbendre yes, we do not log 401 errors. Could your password file be corrupted by some external tools (like security or antivirus software)?

**Comment by jsa34** [comment]
I can't see anything wrong with the password file itself, and the logs for ggr container suggest that it is picking up the correct file for username/pwd

**Comment by jsa34** [comment]
I checked htpasswd -bv users.htpasswd test password, and the username/password is returned as valid

**Comment by jsa34** [comment]
This fixed itself, it seems, again.

I tried deleting and removing the ggr container, and then pulled and started it again, and suddenly it started working.  The only difference between this and this other 5 or 6 times I tried before was I added the guest quota (docker run -d --name ggr -v /etc/grid-router/:/etc/grid-router:ro --net host aerokube/ggr:latest-release **-guests-allowed -guests-quota test**), but I am unconvinced that this was the cause of the solution... Mystery until it, probably, happens again!

**Comment by jsa34** [comment]
As an update:
It looks as though the  -guests-allowed -guests-quota test flags **are** what is causing the tests to successfully be authorised (i.e. it is ignoring the username and password passed in the request).  When I remove these, it continues to fail.  When I try and create a manual container through selenoid-ui (via ggr-ui), upon clicking the desired browser, the button label turns red.  Not sure what is happening, and tried everything I can think of RE: htpasswd file.
