### ISSUE TITLE
Moving GGR to another server

### ISSUE THREAD

**Issue by Pavel077** [aerokube/ggr#358]
Hello.

Is it possible to move GGR process to another server? What would happen to containers running on selenoid backend servers if GGR is shutdown?

**Comment by vania-pooh** [comment]
@Pavel077 We recommend having 2 or more Ggr replicas behind some reverse proxy like Nginx. In that case you can move Ggr replicas one by one and Nginx will do the rest. If you have only one Ggr instance running, then stopping it will certainly break your tests. Browser containers that case will be more probably just removed by Selenoid because of session timeout.

**Comment by Pavel077** [comment]
Thank you!
Removing of browser containers by selenoid due to session timeout is determined by  `-max-timeout`  parameter of selenoid, right?

**Comment by vania-pooh** [comment]
@Pavel077 mainly by `-timeout` flag. `-max-timeout` is the maximum timeout that user can request with `sessionTimeout` capability.

**Comment by Pavel077** [comment]
Thank you!
